# Generated by Django 5.1 on 2024-09-09 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auditentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditEntry',
        ),
    ]
